[package]
name = "keys"
version = "0.1.0"
authors = ["QuantumCoded <bfields32@student.cccs.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyboard_query = "0.1.0"